### ISSUE TITLE
Is this compatible with hapi 8?

### ISSUE THREAD

**Issue by bencooling** [aduis/hapi-rabbit#2]
plugin.events.once('start', function () {
    ...

TypeError: Cannot read property 'once' of undefined

**Comment by aduis** [comment]
No, it's not compatible. I'll work on a fix for this this weekend.

**Comment by aduis** [comment]
Actually, it is working. Just the readme is incorrect...

try this:

var Hapi = require('hapi');
var server = new Hapi.Server();
var hapiRabbit = require('hapi-rabbit');

server.connection(
    {
        port: "9090"
    }
);

var plugins = [{
    {
    register: hapiRabbit,
    options: {
        url: "amqp://localhost"
    }
}];

server.register(plugins, function (err) {
    if (err) {
        console.log('error when registering modules', error);
    }
});

server.start(function (err) {
    if (err) {
        console.log('error when starting server', error);
    }

    var rabbit = server.plugins['hapi-rabbit'];
    rabbit.createContext(function(err, context){
        if(err){
            console.log('err', err);
        }

        rabbit.subscribe(context, 'exchange', function(err, message){
            console.log('message', message);
        });
    });

    console.log('service started');
});

**Comment by bencooling** [comment]
Thank you.
